APPLICATION = noelv_test

BOARD ?= zedboard-noelv
RIOTBASE ?= $(CURDIR)/../..

DEVELHELP ?= 1
QUIET ?= 1

# Use ztimer for delays if timer is available
FEATURES_OPTIONAL += periph_timer

include $(RIOTBASE)/Makefile.include
